# Generated by Django 6.0.1 on 2026-01-16 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Prénom')),
                ('last_name', models.CharField(max_length=100, verbose_name='Nom')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('school', models.CharField(blank=True, max_length=100, null=True, verbose_name='École')),
                ('year', models.CharField(blank=True, max_length=100, null=True, verbose_name='Année')),
                ('promotion', models.CharField(blank=True, max_length=50, null=True, verbose_name='Promotion')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='students_photos/', verbose_name='Photo')),
                ('photo_url', models.URLField(blank=True, null=True, verbose_name='URL photo trombinoscope')),
                ('face_encoding', models.TextField(blank=True, null=True, verbose_name='Encodage facial')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de mise à jour')),
            ],
            options={
                'verbose_name': 'Étudiant',
                'verbose_name_plural': 'Étudiants',
                'ordering': ['last_name', 'first_name'],
                'unique_together': {('first_name', 'last_name', 'email')},
            },
        ),
    ]
